User_name = input("My name is: ")
User_location = input("My location is:")
User_college = input("My college is: ")
print("Name:", User_name)
print("Location:", User_location)
print("College:", User_college)
name = input("name: ")
location = input("location: ")
college = input("college: ")
print(name +  "from"  + location + "is studying at" + college )